# Generated by Django 3.2.19 on 2023-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('bimg', models.ImageField(upload_to='bimg')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
