# Generated by Django 3.2.11 on 2023-06-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_com_mssg'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_mssg',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
