# Generated by Django 3.2.11 on 2023-06-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_com_mssg_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_mssg',
            old_name='status',
            new_name='confirm',
        ),
        migrations.AddField(
            model_name='com_mssg',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
