# Generated by Django 3.2.11 on 2023-06-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20230607_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='com_mssg',
            old_name='confirm',
            new_name='approve',
        ),
    ]
